export const destinations = [
  "Nevada",
  "New Jersey",
  "Delaware",
  "Philadelphia",
  "New York City",
  "San Francisco",
  "Wilmington",
  "Virginia",
  "Virginia Beach",
];

export const recommendedHouses = [
  {
    id: 1,
    img: "https://remap.travelerwp.com/wp-content/uploads/2015/01/2018-08-21-16-38-31-029636-322W20thSt_Kitchen1_23-scaled.jpg",
    cost: 235,
    name: "Best of west village",
    location: "New York City, NY, USA",
    rating: 5,
    reviewsNumber: 1,
    meta: {
      people: 6,
      bed: 1,
      bathroom: 1,
      size: 2160,
    },
  },
  {
    id: 2,
    img: "https://remap.travelerwp.com/wp-content/uploads/2015/01/2017-05-23-21-41-55-187424-BEK865-14-scaled-1200x900.jpg",
    cost: 235,
    name: "Spacious 3 Bedrooms",
    location: "New York City, NY, USA",
    rating: 5,
    reviewsNumber: 1,
    meta: {
      people: 6,
      bed: 1,
      bathroom: 1,
      size: 2160,
    },
  },
  {
    id: 3,
    img: "https://remap.travelerwp.com/wp-content/uploads/2015/01/KBY219-TAKE-01-4-scaled.jpg",
    cost: 235,
    name: "Manhattan Oversized",
    location: "New York City, NY, USA",
    rating: 5,
    reviewsNumber: 1,
    meta: {
      people: 6,
      bed: 1,
      bathroom: 1,
      size: 2160,
    },
  },
  {
    id: 4,
    img: "https://remap.travelerwp.com/wp-content/uploads/2015/01/2018-08-21-16-38-31-029636-322W20thSt_Kitchen1_23-scaled.jpg",
    cost: 235,
    name: "Best of west village",
    location: "New York City, NY, USA",
    rating: 5,
    reviewsNumber: 1,
    meta: {
      people: 6,
      bed: 1,
      bathroom: 1,
      size: 2160,
    },
  },
  {
    id: 5,
    img: "https://remap.travelerwp.com/wp-content/uploads/2015/01/2017-05-23-21-41-55-187424-BEK865-14-scaled-1200x900.jpg",
    cost: 235,
    name: "Spacious 3 Bedrooms",
    location: "New York City, NY, USA",
    rating: 5,
    reviewsNumber: 1,
    meta: {
      people: 6,
      bed: 1,
      bathroom: 1,
      size: 2160,
    },
  },
  {
    id: 6,
    img: "https://remap.travelerwp.com/wp-content/uploads/2015/01/KBY219-TAKE-01-4-scaled.jpg",
    cost: 235,
    name: "Manhattan Oversized",
    location: "New York City, NY, USA",
    rating: 5,
    reviewsNumber: 1,
    meta: {
      people: 6,
      bed: 1,
      bathroom: 1,
      size: 2160,
    },
  },
];

export const reviews = [
  {
    img: "https://remap.travelerwp.com/wp-content/uploads/2019/04/Emmi-100x100.png",
    text: "Faucibus tristique felis potenti ultrices ornare rhoncus semper hac facilisi Rutrum tellus lorem sem velit nisi non pharetra in dui.",
    name: "Eva Hicks",
  },
  {
    img: "https://remap.travelerwp.com/wp-content/uploads/2019/04/Emmi-100x100.png",
    text: "Faucibus tristique felis potenti ultrices ornare rhoncus semper hac facilisi Rutrum tellus lorem sem velit nisi non pharetra in dui.",
    name: "Eva Hicks",
  },
  {
    img: "https://remap.travelerwp.com/wp-content/uploads/2019/04/Emmi-100x100.png",
    text: "Faucibus tristique felis potenti ultrices ornare rhoncus semper hac facilisi Rutrum tellus lorem sem velit nisi non pharetra in dui.",
    name: "Eva Hicks",
  },
  {
    img: "https://remap.travelerwp.com/wp-content/uploads/2019/04/Emmi-100x100.png",
    text: "Faucibus tristique felis potenti ultrices ornare rhoncus semper hac facilisi Rutrum tellus lorem sem velit nisi non pharetra in dui.",
    name: "Eva Hicks",
  },
];
